### ISSUE TITLE
Use Firestore instead of datastore

### ISSUE THREAD

**Issue by fhinkel** [googleapis/nodejs-datastore-session#100]
According to https://cloud.google.com/datastore/, "Cloud Firestore is the next generation of Cloud Datastore", so we really should offer sessions with Firestore.

**Comment by JustinBeckwith** [comment]
Another option is to add a `nodejs-firestore-session` library in addition to this one.  What do you think?

**Comment by fhinkel** [comment]
Sounds good. Should I write it?

**Comment by JustinBeckwith** [comment]
If you're offering, sure!  Happy to do the OSS stuff to create the repo if you like :)

**Comment by fhinkel** [comment]
That would be great if you can open the repo!
