### ISSUE TITLE
README examples with environment variables are broken

### ISSUE THREAD

**Issue by cashpipeplusplus** [googleapis/nodejs-datastore-session#150]
The examples in the README that involve environment variables are broken.  For example:

      projectId: 'YOUR_PROJECT_ID' || process.env.GCLOUD_PROJECT,

In that example, the environment variable will never be used.  Instead, it should come first:

      projectId: process.env.GCLOUD_PROJECT || 'YOUR_PROJECT_ID',

**Comment by BenWhitehead** [comment]
Assigning to @bcoe as he is reviewing the corresponding fix PR #151

**Comment by cashpipeplusplus** [comment]
I've closed the PR, so please feel free to fix this any way you see fit.  Thank you for looking into it.

**Comment by bcoe** [comment]
:wave:  closing in favor of #159, thanks for helping with this @cashpipeplusplus.
