### ISSUE TITLE
Add support for datastore v8

### ISSUE THREAD

**Issue by mbyrne00** [googleapis/nodejs-datastore-session#363]
The versioning of this library seems bound to the version of datastore itself which may not be necessary. See https://github.com/googleapis/nodejs-datastore-session/blob/93e814bcf3823942f2d287653b71a5eba2dcbbde/package.json#L38

Apart from requiring a new minimal version of nodejs (14), [version 8](https://github.com/googleapis/nodejs-datastore/blob/main/CHANGELOG.md#800-2023-08-09) is backwards compatible.

Can you please release a version that allows `peerDependency` including v8.

**Comment by AndrewGnagy** [comment]
As a work-around
```
  "overrides": {
    "@google-cloud/connect-datastore": {
      "@google-cloud/datastore": "$@google-cloud/datastore"
    }
  }
```

**Comment by mbyrne00** [comment]
Thanks for that. The ideal solution would be to put a _minimum_ version in peer dependencies rather than bind to major version, so there is no maintenance burden, with the caveat that it’s only been tested with a certain version.

People can upgrade at their leisure and you can release a new major version whenever you want that mandates a new minimum version.

“>= 7.0.0”
