### ISSUE TITLE
npm install - UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by vvzen** [googleapis/nodejs-datastore-session#5]
While installing, I came across this warning:
![connect_datastore_unmet_peer_dependency](https://cloud.githubusercontent.com/assets/10340139/21847455/4dcb8356-d7fc-11e6-8449-36ad0840dd59.png)

Maybe there's a conflict since I'm currently using the google-datastore package, which I got from _npm install google-cloud_ and I'm using like this :
```
const gcloud = require('google-cloud');
const Datastore = googlecloud.datastore;
```

Is there a way I can use **connect-datastore** without installing another package?
Maybe doing something like
`const DatastoreStore = googlecloud.connectDatastore;` ?

PS: except for this warning, the sessions storing seems to work without errors. 👍

**Comment by jmdobry** [comment]
The `google-cloud` package itself installs `@google-cloud/datastore`, and I was hoping that would satisfy the peer dependency. I'll remove the peer dependency.

**Comment by JustinBeckwith** [comment]
Now that the `google-cloud` metapackage is entirely deprecated, this should be resolved :)
