### ISSUE TITLE
How to properly setup credentials?

### ISSUE THREAD

**Issue by pqvst** [googleapis/nodejs-datastore-session#6]
I have a node.js appengine application. How do I properly setup my credentials so that my app can access the datastore when deployed to appengine?

When I deploy my app, I can see that the `GCLOUD_PROJECT` env var is set. However, the `GOOGLE_APPLICATION_CREDENTIALS` is not set.

I've managed to make it work by executing `gcloud auth application-default login` on my local machine, and then placing the json file in my app source. Is this the correct workflow?

**Comment by RobbyDmz** [comment]
Hi,

I may be a bit late to the party, but maybe this will help other people who stumble upon this issue. When your application is deployed to app engine or on the google cloud compute engine it has access to the datastore databases within it's project, there should be no setup. For localhost (dev) setup you can use a keyfile generated in the IAM section of the Google Cloud Console that has the correct access rights for your project.

Regards,

Robby

**Comment by JustinBeckwith** [comment]
That's correct!  Technically, you shouldn't have to do anything.  It should "just work".  I'm going to close this out for now, but please do let me know if you have any other questions!
