### ISSUE TITLE
`prefix` option doesn't seem to do anything

### ISSUE THREAD

**Issue by pqvst** [googleapis/nodejs-datastore-session#7]
As far as I can tell, the `prefix` option doesn't seem to do anything. I am using `"express-sessions"` as in the example, but I can't see this appearing anywhere when I look through my Datastore in the gcloud console. 

Is this meant to control the `Kind` (which is currently hardcoded as `"Session"`?

**Comment by jake-tulip** [comment]
Datastore uses the `kind` keyword (not prefix) for labelling, currently hardcoded to 'Session' would be a good solution.
