### ISSUE TITLE
How to delete old sessions?

### ISSUE THREAD

**Issue by pqvst** [googleapis/nodejs-datastore-session#8]
Over time sessions will accumulate in the Datastore. Since all cookie information is stored as json in the `data` field, there is no easy way to query for, and clean up, old sessions.

It would be good if at least a `createdAt` field was included in the datastore entity so that we can run a simple query to find (and delete) old sessions.

**Comment by sceee** [comment]
This is really a must-have because it fills up Cloud Datastore indefinitely and there is no easy way to clean it up. Especially since Cloud Datastore does not have a TTL feature.

I can file a PR for this to at least add a separate property for expiresAt.

**Comment by jmcombs** [comment]
Is this still an open PR in 2019? We need a way to clear expired sessions in Google Cloud Datastore.
